import { GetServerSidePropsContext } from 'next';
import Head from 'next/head'
import {Header} from '../components/Header'
import { TopBar } from '@/components/TopBar';
import { HomeHeroCategories } from '@/components/HomeHeroCategories';
import { Categories } from './models/Categories';
import { Box, Container, Flex } from '@chakra-ui/react';
import { AdvantageItem } from '@/components/AdvantageItem';
import { faTruck, faDesktop, faUndo } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon as FaIcon } from  '@fortawesome/react-fontawesome';


type Product={
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  imag: string;
  rating:{
    count:number;
    rate: number;
  }
}

type Props= {
  products: Product[],
  categories : Categories[]
}

export default function Home({products, categories}: Props) {
  return (
    <>
      <Head>
        <title>Overlap Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar/>
        <Box marginBottom='2rem'>
          <Header/>
        </Box>
        <Container size='lg'>
          <HomeHeroCategories categories={categories}></HomeHeroCategories>
          <Flex gap='2rem' justifyContent='space-between ' margin='2rem 0 '>
            <AdvantageItem
                title='Envio Gratis'
                content='Para ordenes mayores a $10.000'
                icon={faTruck}
                >
            </AdvantageItem>
            <AdvantageItem
                title='Reembolso'
                content='10 dias para regresar tu compra'
                icon={faUndo} 
                >
            </AdvantageItem>
            <AdvantageItem
                title='Soporte'
                content='soporte las 24 hs'
                icon={faDesktop}
                >
            </AdvantageItem>

          </Flex >
        </Container>

        {/* <ol>
          {products.map(product =>{
            return <li key={product.id}>{product.title}</li>
        })}
        </ol> */}
      </main>
    </>
  )
}

export async function getServerSideProps(context : GetServerSidePropsContext){
  
  const products = await fetch('https://fakestoreapi.com/products')
                        .then(res=>res.json())
  const categories = await fetch('https://fakestoreapi.com/products/categories')
                        .then(res=>res.json())

  return{
    props: {
      products,
      categories
      
    }
    
  }
}
