import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { Header } from "../components/Header";
import { TopBar } from "@/components/TopBar";
import { HomeHeroCategories } from "@/components/HomeHeroCategories";
import { Categories } from "./models/Categories";
import { Box, Container, Heading } from "@chakra-ui/react";
import { AdvantageSection } from "@/components/AdvantageSection";
import { ProductSection } from "@/components/ProductSection";
import {
  GroupedProducts,
  groupProductsByCategory,
} from "@/utils/groupProductsByCategory";
import { BannerSection } from "@/components/BannerSection";

export type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
};

export type Props = {
  products: Product[];
  categories: Categories[];
  productsGroupedByCategory: GroupedProducts;
};

export default function Home({
  products,
  categories,
  productsGroupedByCategory,
}: Props) {
  return (
    <>
      <Head>
        <title>Overlap Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar />
        <Box marginBottom="2rem">
          <Header />
        </Box>
        <Container size={{ lg: "lg" }}>
          <HomeHeroCategories categories={categories}></HomeHeroCategories>
          <AdvantageSection />
        </Container>
        <Container
          maxWidth={{
            base: "100%",
            md: "1110px",
          }}
          padding={0}
        >
          {/* <ProductSection products={products} categories={[]} productsGroupedByCategory={productsGroupedByCategory} /> */}
          {Object.entries(productsGroupedByCategory).map(
            ([category, products]) => {
              return (
                <Box key={category} marginBottom="4rem">
                  <Heading
                    as="h2"
                    size="md"
                    textTransform="uppercase"
                    margin={{
                      base: "0 0 1rem 1rem",
                      md: "0 0 2rem 0",
                    }}
                  >
                    {category}
                  </Heading>
                  <ProductSection
                    products={products}
                    categories={[]}
                    productsGroupedByCategory={productsGroupedByCategory}
                  />
                </Box>
              );
            }
          )}
        </Container>
        <Container
          maxWidth={{
            base: "100%",
            md: "1110px",
          }}
        >
          <BannerSection></BannerSection>
        </Container>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  const categories = await fetch(
    "https://fakestoreapi.com/products/categories"
  ).then((res) => res.json());

  const productsGroupedByCategory = groupProductsByCategory(products);

  return {
    props: {
      products,
      categories,
      productsGroupedByCategory,
    },
  };
}
